"""Added 'translation' col to Play table

Revision ID: 1b021a2a9a0e
Revises: e442c820e817
Create Date: 2023-11-03 12:27:27.238885

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1b021a2a9a0e'
down_revision = 'e442c820e817'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play', sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('playtranslations', sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playtranslations', 'translation')
    op.drop_column('play', 'translation')
    # ### end Alembic commands ###
