"""Changed 'translation' to 'translator' in Play table

Revision ID: 64af634f4b33
Revises: 1b021a2a9a0e
Create Date: 2023-11-03 14:48:39.284118

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64af634f4b33'
down_revision = '1b021a2a9a0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play', sa.Column('translator', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('play', 'translation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play', sa.Column('translation', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('play', 'translator')
    # ### end Alembic commands ###
