"""Renamed play_slug to slug in  PlayTranslations

Revision ID: bbd9aaac0f5e
Revises: eb542349a520
Create Date: 2023-09-17 13:50:38.942581

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbd9aaac0f5e'
down_revision = 'eb542349a520'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playtranslations', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'playtranslations', 'play', ['slug'], ['slug'])
    op.drop_column('playtranslations', 'play_slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playtranslations', sa.Column('play_slug', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'playtranslations', type_='foreignkey')
    op.drop_column('playtranslations', 'slug')
    # ### end Alembic commands ###
