"""Changed some indices

Revision ID: e442c820e817
Revises: e65020603943
Create Date: 2023-10-25 15:45:48.478233

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e442c820e817'
down_revision = 'e65020603943'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('play', 'theater',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_play_director', table_name='play')
    op.drop_index('ix_play_theater', table_name='play')
    op.create_index(op.f('ix_play_genre'), 'play', ['genre'], unique=False)
    op.drop_index('ix_playtranslations_director', table_name='playtranslations')
    op.drop_index('ix_playtranslations_genre', table_name='playtranslations')
    op.drop_index('ix_playtranslations_name', table_name='playtranslations')
    op.drop_index('ix_playtranslations_stage', table_name='playtranslations')
    op.drop_index('ix_playtranslations_theater', table_name='playtranslations')
    op.create_index(op.f('ix_playtranslations_play_id'), 'playtranslations', ['play_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playtranslations_play_id'), table_name='playtranslations')
    op.create_index('ix_playtranslations_theater', 'playtranslations', ['theater'], unique=False)
    op.create_index('ix_playtranslations_stage', 'playtranslations', ['stage'], unique=False)
    op.create_index('ix_playtranslations_name', 'playtranslations', ['name'], unique=False)
    op.create_index('ix_playtranslations_genre', 'playtranslations', ['genre'], unique=False)
    op.create_index('ix_playtranslations_director', 'playtranslations', ['director'], unique=False)
    op.drop_index(op.f('ix_play_genre'), table_name='play')
    op.create_index('ix_play_theater', 'play', ['theater'], unique=False)
    op.create_index('ix_play_director', 'play', ['director'], unique=False)
    op.alter_column('play', 'theater',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
