"""Test migration

Revision ID: e65020603943
Revises: bbd9aaac0f5e
Create Date: 2023-09-17 13:52:31.822780

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e65020603943'
down_revision = 'bbd9aaac0f5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
