"""Changed 'play_slug' in  PlayTranslations

Revision ID: eb542349a520
Revises: 
Create Date: 2023-09-17 13:27:36.115689

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'eb542349a520'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('playtranslations_ibfk_2', 'playtranslations', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('playtranslations_ibfk_2', 'playtranslations', 'play', ['play_slug'], ['name'])
    # ### end Alembic commands ###
